[project]
name = "ProjectStructure"
version = "1.2.0"
description = "This creates a structure"
tags = ["project", "folder", "structure", "da4ndo"]

[structure]
"." = ["projectstructure", "Cargo.toml", ".projectstructureignore", "Cargo.lock", "projectstructure.toml"]
"./src" = ["config.rs", "save.rs", "main.rs", "update.rs", "scan.rs", "projectstructure.toml"]
"./src/asd2" = ["asd2.py"]
"./src/asd2/asd3" = []
